version: '3.7'
services:
  mongo:
    image: mongo:3
    container_name: "mongo"
    hostname: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - './.volumes/mongo/data:/data/db'
    networks:
      - netflix-network
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes: 
      - './.volumes/rabbitmq/data:/var/lib/rabbitmq'
      - './.volumes/rabbitmq/log:/var/log/rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_USER=guest
    networks:
      - netflix-network
  grafana:
    image: grafana/grafana:5.4.3
    ports:
      - 3000:3000
    volumes:
      - './.volumes/grafana:/var/lib/grafana'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      netflix-network:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus:v2.6.1
    ports:
      - 9090:9090
    volumes:
      # - './.volumes/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml'
      - './.volumes/prometheus/data:/prometheus'
    networks:
      netflix-network:
        aliases:
          - prometheus
networks:
  netflix-network:
    driver: bridge